### ISSUE TITLE
[REQ] Stirling's Approximation

### ISSUE THREAD

**Issue by luke-bhan** [ayazhafiz/code-weekly#6]
Difficulty:
- [x] Easy

<Describe your exercise and its merits>

The factorial has long been studied in computer programming and it's as simple as `5! = 5 * 4 * 3 * 2 * 1`; however, most programming languages or libraries that include the factorial as a function compute it in O(n) time. Find a way to APPROXIMATE the factorial in O(logn) time. Hint: Most likely you will need to use your code from Week 1.

**Comment by ayazhafiz** [comment]
I really like this. We'll probably make this week 3.

**Comment by ayazhafiz** [comment]
Should we provide Sterling's formula for the approximation? I think it would be non-intuitive to derive individually.

**Comment by luke-bhan** [comment]
Oh yeah I forgot to add that. There’s no way someone could figure it out
that easily.

**Comment by ayazhafiz** [comment]
@luke-bhan do you want to assign the creation of this for next week's exercise for yourself? if not, I'm happy to cake over.

**Comment by luke-bhan** [comment]
I would say yes, but I don’t have the time right now. Unless your open to
moving it to week 4?

**Comment by ayazhafiz** [comment]
All good, I don't want too much space between this and week 01 so I'll take care of it. I'll tag you again when I submit a PR.

**Comment by ayazhafiz** [comment]
PR closed with ba41d69adbc4c505db6e8ea2adcd4f0bbb8f02f8.
